version: "3.7"
services: 
  mysql:
    image: team4qa/database:latest
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
      

  backend:
    image: team4qa/back:latest
    ports:
    - target: 9966
      published: 9966
      protocol: tcp


  frontend:
    image: team4qa/front:latest
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
    - backend 