version: "3.7"
services: 
  mysql:
    build: ./database
    #image: team4qa/database:latest
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
      

  backend:
    build: ./backend
    #image: team4qa/backend:latest
    ports:
    - target: 9966
      published: 9966
      protocol: tcp


  frontend:
    build: ./front
    #image: team4qa/frontend:latest
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
    - backend 
